INSERT INTO SIMPLE_BOARD(TITLE, CONTENT) VALUES('자동생성 - 제목1', '자동생성 - 내용1');
INSERT INTO SIMPLE_BOARD(TITLE, CONTENT) VALUES('자동생성 - 제목2', '자동생성 - 내용2');
INSERT INTO SIMPLE_BOARD(TITLE, CONTENT) VALUES('자동생성 - 제목3', '자동생성 - 내용3');
INSERT INTO SIMPLE_BOARD(TITLE, CONTENT) VALUES('자동생성 - 제목4', '자동생성 - 내용4');